# Generated by Django 5.2.13 on 2026-04-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
