# Generated by Django 6.0.4 on 2026-04-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_latitude_accommodation_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
