# Generated by Django 5.2.13 on 2026-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accommodation_ma_khach_san_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='ma_khach_san',
            new_name='accommodation_code',
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='so_lan_danh_gia',
            new_name='review_count',
        ),
        migrations.AlterField(
            model_name='accommodationreview',
            name='score',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
