# Generated by Django 6.0.4 on 2026-04-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0003_accommodation_image_url'),
        ('accommodations', '0004_rename_ma_khach_san_accommodation_accommodation_code_and_more'),
    ]

    operations = [
    ]
