# Generated by Django 5.2.13 on 2026-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('price_per_night', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('rating', models.FloatField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
