# Generated by Django 5.2.13 on 2026-04-14 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0005_merge_20260411_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='hotline',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodationreview',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accommodations.accommodation'),
        ),
    ]
