# Generated by Django 5.2.13 on 2026-04-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0006_accommodation_hotline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='price_per_night',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('dorm', 'Dorm'), ('other', 'Other')], default='single', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('price_per_night', models.IntegerField()),
                ('capacity', models.IntegerField(default=1)),
                ('total_rooms', models.IntegerField(default=1)),
                ('available_rooms', models.IntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodations.accommodation')),
            ],
        ),
    ]
