# Generated by Django 4.2.9 on 2026-05-21 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0008_alter_accommodation_hotline_alter_accommodation_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAccommodationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('hotel_name', models.CharField(max_length=200)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], default='hotel', max_length=20)),
                ('area', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('price_per_night', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=1)),
                ('hotline', models.CharField(blank=True, max_length=50)),
                ('amenities_text', models.TextField(blank=True, help_text='Nhập tiện ích, cách nhau bằng dấu phẩy. Ví dụ: Wifi, Hồ bơi, Gần biển')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('google_maps_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã thêm vào Accommodation'), ('rejected', 'Từ chối')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_requests', to='accommodations.accommodation')),
            ],
            options={
                'verbose_name': 'Yêu cầu hợp tác khách sạn',
                'verbose_name_plural': 'Yêu cầu hợp tác khách sạn',
                'ordering': ['-created_at'],
            },
        ),
    ]
