# Generated by Django 4.2.9 on 2026-05-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0009_partneraccommodationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partneraccommodationrequest',
            name='amenities_text',
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_name',
            field=models.CharField(default='Standard Room', max_length=100),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_price_per_night',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='room_type',
            field=models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Suite'), ('dorm', 'Dorm'), ('other', 'Other')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='partneraccommodationrequest',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
