# Generated by Django 4.2.9 on 2026-05-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0010_remove_partneraccommodationrequest_amenities_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='image_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
