"""
Django settings for accommodation_project project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = BASE_DIR.parent.parent

ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    load_dotenv(ENV_PATH)
else:
    load_dotenv(REPO_ROOT / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m24lci=zdve8=(8!%5&r^*)pdokrgvufxu)3tq5+3c-^egh#fs'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'accommodations',
    'preferences',
    'recommendations',
    'accounts',
    'chat_api',
    'voice_api',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'accommodation_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accommodation_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
     #"default": {
         #"ENGINE": "mssql",
         #"NAME": "AccommodationDB",
         #"HOST": "localhost",
         #"PORT": "",
         #"OPTIONS": {
             #"driver": "ODBC Driver 17 for SQL Server",
             #"trusted_connection": "yes",
             #"extra_params": "Encrypt=no;TrustServerCertificate=yes;",
         #},
     #}

    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

FIREBASE_API_KEY = os.getenv('FIREBASE_API_KEY', '')
FIREBASE_AUTH_DOMAIN = os.getenv('FIREBASE_AUTH_DOMAIN', '')
FIREBASE_DATABASE_URL = os.getenv('FIREBASE_DATABASE_URL', '')
FIREBASE_PROJECT_ID = os.getenv('FIREBASE_PROJECT_ID', '')
FIREBASE_STORAGE_BUCKET = os.getenv('FIREBASE_STORAGE_BUCKET', '')
FIREBASE_MESSAGING_SENDER_ID = os.getenv('FIREBASE_MESSAGING_SENDER_ID', '')
FIREBASE_APP_ID = os.getenv('FIREBASE_APP_ID', '')
FIREBASE_MEASUREMENT_ID = os.getenv('FIREBASE_MEASUREMENT_ID', '')
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:8000')
GOOGLE_URL = os.getenv('GOOGLE_URL', '')
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
GOOGLE_REDIRECT_URI = os.getenv('GOOGLE_REDIRECT_URI', '')
FIREBASE_WEB_API_KEY = os.getenv('FIREBASE_WEB_API_KEY', FIREBASE_API_KEY)
COOKIE_SECURE = os.getenv('COOKIE_SECURE', 'false').lower() in {'1', 'true', 'yes'}

FIREBASE_ADMIN_CONFIG = {
    'type': os.getenv('FIREBASE_ADMIN_TYPE', ''),
    'project_id': os.getenv('FIREBASE_ADMIN_PROJECT_ID', ''),
    'private_key_id': os.getenv('FIREBASE_ADMIN_PRIVATE_KEY_ID', ''),
    'private_key': os.getenv('FIREBASE_ADMIN_PRIVATE_KEY', ''),
    'client_email': os.getenv('FIREBASE_ADMIN_CLIENT_EMAIL', ''),
    'client_id': os.getenv('FIREBASE_ADMIN_CLIENT_ID', ''),
    'auth_uri': os.getenv('FIREBASE_ADMIN_AUTH_URI', ''),
    'token_uri': os.getenv('FIREBASE_ADMIN_TOKEN_URI', ''),
    'auth_provider_x509_cert_url': os.getenv(
        'FIREBASE_ADMIN_AUTH_PROVIDER_X509_CERT_URL',
        '',
    ),
    'client_x509_cert_url': os.getenv('FIREBASE_ADMIN_CLIENT_X509_CERT_URL', ''),
    'universe_domain': os.getenv('FIREBASE_ADMIN_UNIVERSE_DOMAIN', ''),
}

FIREBASE_WEB_CONFIG = {
    'apiKey': FIREBASE_API_KEY,
    'authDomain': FIREBASE_AUTH_DOMAIN,
    'databaseURL': FIREBASE_DATABASE_URL,
    'projectId': FIREBASE_PROJECT_ID,
    'storageBucket': FIREBASE_STORAGE_BUCKET,
    'messagingSenderId': FIREBASE_MESSAGING_SENDER_ID,
    'appId': FIREBASE_APP_ID,
    'measurementId': FIREBASE_MEASUREMENT_ID,
}

GOOGLE_LOGIN = {
    'google_url': GOOGLE_URL,
    'google_client_id': GOOGLE_CLIENT_ID,
    'google_client_secret': GOOGLE_CLIENT_SECRET,
    'google_redirect_uri': GOOGLE_REDIRECT_URI,
    'firebase_web_api_key': FIREBASE_WEB_API_KEY,
    'frontend_url': FRONTEND_URL,
    'cookie_secure': COOKIE_SECURE,
}


try:
    from . import settings_local as local_settings

    if hasattr(local_settings, "DATABASE_OVERRIDES"):
        for key, value in local_settings.DATABASE_OVERRIDES.items():
            if key == "OPTIONS" and isinstance(value, dict):
                DATABASES["default"].setdefault("OPTIONS", {})
                DATABASES["default"]["OPTIONS"].update(value)
            else:
                DATABASES["default"][key] = value

    if hasattr(local_settings, "STATICFILES_DIRS"):
        STATICFILES_DIRS = local_settings.STATICFILES_DIRS

except ImportError:
    pass
