# Generated by Django 5.2.13 on 2026-04-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('guest_count', models.IntegerField()),
                ('preferred_type', models.CharField(choices=[('hotel', 'Hotel'), ('homestay', 'Homestay'), ('hostel', 'Hostel'), ('apartment', 'Apartment')], max_length=20)),
                ('required_amenities', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
