# Generated by Django 4.2.9 on 2026-05-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_alter_userpreference_preferred_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='search_radius_km',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='user_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
