# Generated by Codex on 2026-05-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0003_userpreference_search_radius_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='anchor_kind',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='filter_tree_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='location_label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='location_mode',
            field=models.CharField(blank=True, default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='soft_filter_summary',
            field=models.TextField(blank=True),
        ),
    ]
