TYPE_PATTERNS = [
    (r"(?<!\w)(khách sạn|khach san|hotel|ks)(?!\w)", "hotel"),
    (r"(?<!\w)(homestay|home stay)(?!\w)", "homestay"),
    (r"(?<!\w)(hostel|nhà nghỉ|nha nghi|dorm)(?!\w)", "hostel"),
    (r"(?<!\w)(căn hộ|apartment|chung cư|chung cu)(?!\w)", "apartment"),
]
# Resort is recognized but intentionally not enabled as preferred_type because
# chat_api.schema.ALLOWED_TYPES is still synced to downstream recommend types:
# hotel/homestay/hostel/apartment.
UNSUPPORTED_TYPE_PATTERNS = [
    (r"(?<!\w)(resort|khu nghỉ dưỡng|khu nghi duong)(?!\w)", "resort"),
]

AMENITY_MAP = {
    "wifi": "wifi",
    "wi-fi": "wifi",
    "internet": "wifi",

    "hồ bơi": "pool",
    "bể bơi": "pool",
    "pool": "pool",

    "bãi đỗ xe": "parking",
    "chỗ đậu xe": "parking",
    "gửi xe": "parking",
    "đậu ô tô": "parking",
    "đậu xe hơi": "parking",
    "parking": "parking",

    "máy lạnh": "air_conditioner",
    "điều hòa": "air_conditioner",
    "air conditioner": "air_conditioner",
    "ac": "air_conditioner",
    "aircon": "air_conditioner",

    "ăn sáng": "breakfast",
    "buffet sáng": "breakfast",
    "breakfast": "breakfast",

    "ban công": "balcony",
    "balcony": "balcony",

    "bồn tắm": "bathtub",
    "bathtub": "bathtub",
    "bath tub": "bathtub",
    "tub": "bathtub",

    "bếp": "kitchen",
    "nhà bếp": "kitchen",
    "kitchen": "kitchen",
    "nấu ăn": "kitchen",

    "máy giặt": "washing_machine",
    "washing machine": "washing_machine",
}
# Elevator/lift aliases are intentionally not mapped until downstream recommend
# exposes a compatible amenity key. Do not coerce them into elderly_friendly.

PRIORITY_MAP = {
    "gần trung tâm": "near_center",
    "near center": "near_center",
    "near the center": "near_center",
    "close to center": "near_center",
    "close to the center": "near_center",
    "near downtown": "near_center",
    "central": "near_center",
    "gần phố cổ": "near_center",

    "gần biển": "near_beach",
    "gần bãi biển": "near_beach",
    "near beach": "near_beach",
    "near the beach": "near_beach",
    "close to beach": "near_beach",
    "by the beach": "near_beach",
    "beachfront": "near_beach",

    "rẻ": "cheap",
    "giá rẻ": "cheap",
    "giá mềm": "cheap",
    "cheap": "cheap",
    "affordable": "cheap",

    "yên tĩnh": "quiet",
    "ít ồn": "quiet",
    "không ồn": "quiet",
    "không quá ồn": "quiet",
    "đừng ồn": "quiet",
    "quiet": "quiet",

    "rating cao": "high_rating",
    "đánh giá cao": "high_rating",
    "high rating": "high_rating",

    "view đẹp": "nice_view",
    "cảnh đẹp": "nice_view",
    "nice view": "nice_view",
    "chụp hình đẹp": "nice_view",
    "view núi": "nice_view",
    "view rừng": "nice_view",
    "view đồi": "nice_view",
    "mountain view": "nice_view",
    "forest view": "nice_view",
    "hill view": "nice_view",
}

SPECIAL_REQUIREMENT_MAP = {
    "có em bé": "baby_friendly",
    "trẻ nhỏ": "baby_friendly",
    "bé nhỏ": "baby_friendly",
    "em bé": "baby_friendly",
    "kid": "baby_friendly",
    "kids": "baby_friendly",
    "child": "baby_friendly",
    "children": "baby_friendly",

    "người lớn tuổi": "elderly_friendly",
    "có người già": "elderly_friendly",
    "ông bà": "elderly_friendly",
    "lớn tuổi": "elderly_friendly",

    "thú cưng": "pet_friendly",
    "mang theo thú cưng": "pet_friendly",
    "mang theo pet": "pet_friendly",
    "mang chó": "pet_friendly",
    "mang mèo": "pet_friendly",
    "1 chó": "pet_friendly",
    "1 mèo": "pet_friendly",
    "with dog": "pet_friendly",
    "with a dog": "pet_friendly",
    "with cat": "pet_friendly",
    "with a cat": "pet_friendly",
    "dog": "pet_friendly",
    "cat": "pet_friendly",
    "pet": "pet_friendly",
    "pet-friendly": "pet_friendly",
    "pet friendly": "pet_friendly",
    "with pet": "pet_friendly",

    "làm việc": "work_friendly",
    "công tác": "work_friendly",
    "workation": "work_friendly",
    "work-friendly": "work_friendly",
    "work friendly": "work_friendly",
    "remote work": "work_friendly",
    "remote working": "work_friendly",
    "remote-work": "work_friendly",
    "vừa nghỉ vừa làm": "work_friendly",
    "để làm việc": "work_friendly",
    "không gian làm việc": "work_friendly",
    "xuất hóa đơn": "work_friendly",

    "riêng tư": "private",
    "private": "private",

    "an toàn": "safe_area",
    "safe": "safe_area",
}

AREA_ALIASES = {
    "tp hcm": [
        "tp hcm",
        "hcm",
        "hcmc",
        "ho chi minh",
        "ho chi minh city",
        "hồ chí minh",
        "tp hồ chí minh",
        "sai gon",
        "sài gòn",
        "sg",
    ],
    "đà lạt": ["da lat", "đà lạt"],
    "đà nẵng": ["da nang", "đà nẵng"],
    "hội an": ["hoi an", "hội an"],
    "huế": ["hue", "huế"],
    "nha trang": ["nha trang"],
    "vũng tàu": ["vung tau", "vũng tàu"],
    "hà nội": ["ha noi", "hà nội", "hanoi"],
    "phú quốc": ["phu quoc", "phú quốc"],
    "mũi né": ["mui ne", "mũi né"],
    "sapa": ["sa pa", "sapa"],
    "quy nhơn": ["quy nhon", "quy nhơn"],
    "cần thơ": ["can tho", "cần thơ"],
    "phan thiết": ["phan thiet", "phan thiết"],
}

LANDMARK_ALIASES = {
    "bến thành": "quận 1 tp hcm",
    "ben thanh": "quận 1 tp hcm",
    "tân sơn nhất": "tân bình tp hcm",
    "tan son nhat": "tân bình tp hcm",
    "bến xe miền đông": "bình thạnh tp hcm",
    "ben xe mien dong": "bình thạnh tp hcm",
    "chợ rẫy": "quận 5 tp hcm",
    "cho ray": "quận 5 tp hcm",
    "phố cổ hà nội": "hà nội",
    "pho co ha noi": "hà nội",
    "old quarter": "hà nội",
    "phố cổ": "hà nội",
    "pho co": "hà nội",
    "đại nội": "huế",
    "dai noi": "huế",
    "landmark 81": "tp hcm",
    "crescent mall": "quận 7 tp hcm",
    "my khe": "đà nẵng",
    "mỹ khê": "đà nẵng",
    "nội bài": "hà nội",
    "noi bai": "hà nội",
    "sân bay nội bài": "hà nội",
    "san bay noi bai": "hà nội",
    "sân bay tân sơn nhất": "tân bình tp hcm",
    "san bay tan son nhat": "tân bình tp hcm",
    "da nang airport": "đà nẵng",
    "sân bay đà nẵng": "đà nẵng",
    "san bay da nang": "đà nẵng",
}
# Generic "near airport" is intentionally ignored unless a named airport appears.

NEGATION_CUES = [
    "không cần",
    "không muốn",
    "không thích",
    "ko cần",
    "ko muốn",
    "không",
    "dont",
    "don't",
    "no need",
]

NUMBER_WORDS = {
    "mot": 1,
    "một": 1,
    "hai": 2,
    "ba": 3,
    "bon": 4,
    "bốn": 4,
    "tu": 4,
    "tư": 4,
    "nam": 5,
    "năm": 5,
    "sau": 6,
    "sáu": 6,
    "bay": 7,
    "bảy": 7,
    "tam": 8,
    "tám": 8,
    "chin": 9,
    "chín": 9,
    "muoi": 10,
    "mười": 10,
    "one": 1,
    "two": 2,
    "three": 3,
    "four": 4,
    "five": 5,
    "six": 6,
    "seven": 7,
    "eight": 8,
    "nine": 9,
    "ten": 10,
}
